services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - msa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # [추가] 유레카 서버 (가장 먼저 켜져야 함)
  discoveryservice:
    build: ./discoveryservice
    container_name: discoveryservice
    ports:
      - "8761:8761"
    networks:
      - msa-network

  userservice:
    build: ./userservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      # [추가] 유레카 서버 주소 알려주기
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:8761/eureka/
    depends_on:
      mysqldb:
        condition: service_healthy
      discoveryservice:
        condition: service_started
    networks:
      - msa-network

  orderservice:
    build: ./orderservice
    ports:
      - "8082-8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # [추가] 유레카 서버 주소 알려주기
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:8761/eureka/
    depends_on:
      mysqldb:
        condition: service_healthy
      discoveryservice:
        condition: service_started
    networks:
      - msa-network

  apigateway:
    build: ./apigateway
    container_name: apigateway
    ports:
      - "8000:8000"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:8761/eureka/
    depends_on:
      - discoveryservice
    networks:
      - msa-network

  configservice:
    build:
      context: ./configservice
      dockerfile: Dockerfile
    container_name: configservice
    ports:
      - "8888:8888"
    networks:
      - msa-network
    depends_on:
      - discoveryservice

networks:
  msa-network:
    driver: bridge