name: Java CI/CD with Docker for User Service

on:
  push:
    branches: [ "main", "ci/github-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1. 자바 버전 21로 수정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 2. Gradle 8.7을 이용한 빌드
      # JAR 파일만 생성하여 Docker로 넘겨주기 위해 build 수행
      - name: Build with Gradle
        run: ./gradlew :userservice:clean :userservice:bootJar -x test

      # 3. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 4. Docker 이미지 빌드 및 푸시
      # 빌드된 JAR를 사용하도록 context와 Dockerfile을 연동합니다.
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: . # 최상위 루트 기준
          file: ./userservice/Dockerfile # Dockerfile 위치 명시
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest